// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfeYGM1sMNH5_pNDBFIfDNLMfZJ7k5Evw',
    appId: '1:822845398511:web:d7eed19c92966e95d02a1a',
    messagingSenderId: '822845398511',
    projectId: 'doctor-appointment-proje-77d3f',
    authDomain: 'doctor-appointment-proje-77d3f.firebaseapp.com',
    storageBucket: 'doctor-appointment-proje-77d3f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDAzSB7QvaQOG_VoUbVFbN9qYgrWRIeAM',
    appId: '1:822845398511:android:3783113b10d63a54d02a1a',
    messagingSenderId: '822845398511',
    projectId: 'doctor-appointment-proje-77d3f',
    storageBucket: 'doctor-appointment-proje-77d3f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW1ioPDAbFD8IBbcTznC12BQSlesB3edw',
    appId: '1:822845398511:ios:e5cc524b059c487ed02a1a',
    messagingSenderId: '822845398511',
    projectId: 'doctor-appointment-proje-77d3f',
    storageBucket: 'doctor-appointment-proje-77d3f.firebasestorage.app',
    iosBundleId: 'com.example.doctorAppointmentProyect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDW1ioPDAbFD8IBbcTznC12BQSlesB3edw',
    appId: '1:822845398511:ios:e5cc524b059c487ed02a1a',
    messagingSenderId: '822845398511',
    projectId: 'doctor-appointment-proje-77d3f',
    storageBucket: 'doctor-appointment-proje-77d3f.firebasestorage.app',
    iosBundleId: 'com.example.doctorAppointmentProyect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfeYGM1sMNH5_pNDBFIfDNLMfZJ7k5Evw',
    appId: '1:822845398511:web:e78cc7fd1a162859d02a1a',
    messagingSenderId: '822845398511',
    projectId: 'doctor-appointment-proje-77d3f',
    authDomain: 'doctor-appointment-proje-77d3f.firebaseapp.com',
    storageBucket: 'doctor-appointment-proje-77d3f.firebasestorage.app',
  );

}