// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfuMEaz8mUQLfPj9gkT95XmJgvHTNqftA',
    appId: '1:297165139509:web:1634e5d365e3ee903ccb7c',
    messagingSenderId: '297165139509',
    projectId: 'doctorappointmentapp-d02ad',
    authDomain: 'doctorappointmentapp-d02ad.firebaseapp.com',
    storageBucket: 'doctorappointmentapp-d02ad.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcqQKpsvpMXFBFhjOOzrJwZNScpyCXruY',
    appId: '1:297165139509:android:195800b07dd2f44f3ccb7c',
    messagingSenderId: '297165139509',
    projectId: 'doctorappointmentapp-d02ad',
    storageBucket: 'doctorappointmentapp-d02ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbZiCICT0oX-xnxy4ILwnhq-btHT6_IPg',
    appId: '1:297165139509:ios:bf532592b5d6e7213ccb7c',
    messagingSenderId: '297165139509',
    projectId: 'doctorappointmentapp-d02ad',
    storageBucket: 'doctorappointmentapp-d02ad.firebasestorage.app',
    iosBundleId: 'com.example.doctorAppointmentProyect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbZiCICT0oX-xnxy4ILwnhq-btHT6_IPg',
    appId: '1:297165139509:ios:bf532592b5d6e7213ccb7c',
    messagingSenderId: '297165139509',
    projectId: 'doctorappointmentapp-d02ad',
    storageBucket: 'doctorappointmentapp-d02ad.firebasestorage.app',
    iosBundleId: 'com.example.doctorAppointmentProyect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfuMEaz8mUQLfPj9gkT95XmJgvHTNqftA',
    appId: '1:297165139509:web:5dc65dfd1b6c6c073ccb7c',
    messagingSenderId: '297165139509',
    projectId: 'doctorappointmentapp-d02ad',
    authDomain: 'doctorappointmentapp-d02ad.firebaseapp.com',
    storageBucket: 'doctorappointmentapp-d02ad.firebasestorage.app',
  );
}
