// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm8Xm9jg5axaQN2C2r0V1XgUCyzbf6Z1g',
    appId: '1:521987591979:web:8466121ce1615d47e17f6e',
    messagingSenderId: '521987591979',
    projectId: 'doctor-appointment-proyect',
    authDomain: 'doctor-appointment-proyect.firebaseapp.com',
    storageBucket: 'doctor-appointment-proyect.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-WOlj5Bcwpi3TUEY0_ztAfN6ub8nzlDU',
    appId: '1:521987591979:android:bf5105f9c57bb3d4e17f6e',
    messagingSenderId: '521987591979',
    projectId: 'doctor-appointment-proyect',
    storageBucket: 'doctor-appointment-proyect.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyE1jv8bYMDXd9hPo-jloxfTeY7mXeXWo',
    appId: '1:521987591979:ios:7c2223c899be6232e17f6e',
    messagingSenderId: '521987591979',
    projectId: 'doctor-appointment-proyect',
    storageBucket: 'doctor-appointment-proyect.firebasestorage.app',
    iosBundleId: 'com.example.doctorAppointmentProyect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyE1jv8bYMDXd9hPo-jloxfTeY7mXeXWo',
    appId: '1:521987591979:ios:7c2223c899be6232e17f6e',
    messagingSenderId: '521987591979',
    projectId: 'doctor-appointment-proyect',
    storageBucket: 'doctor-appointment-proyect.firebasestorage.app',
    iosBundleId: 'com.example.doctorAppointmentProyect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBm8Xm9jg5axaQN2C2r0V1XgUCyzbf6Z1g',
    appId: '1:521987591979:web:a02c0b4882b16381e17f6e',
    messagingSenderId: '521987591979',
    projectId: 'doctor-appointment-proyect',
    authDomain: 'doctor-appointment-proyect.firebaseapp.com',
    storageBucket: 'doctor-appointment-proyect.firebasestorage.app',
  );

}